project:
  type: website

website:
  title: "SEPA cuánto paga"
  navbar:
    left:
      - href: storytelling.qmd
        text: Análisis de precios
      - href: metodologia.qmd
        text: Metodología

format:
  html:
    toc: false
      
