project:
  type: website
  output-dir: docs

website:
  title: "SEPA cuánto paga"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Análisis de precios
      - href: metodologia.qmd
        text: Metodología

format:
  html:
    css: styles.css
    toc: false
      
editor: visual
